on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
jobs:
  build:
    name: Whines every hour
    runs-on:  ubuntu-latest
    steps:
      - name: Whiner Bot 
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: python complain.py
